# Nombre del microservicio
spring.application.name=cafeteria-service

# Puerto donde queda escuchando
server.port=8080

# Base de datos H2 en memoria: se crea sola al arrancar y se borra al apagar
spring.datasource.url=jdbc:h2:mem:cafeteriadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate crea las tablas automaticamente a partir de las clases @Entity
spring.jpa.hibernate.ddl-auto=create-drop

# Hace que data.sql se ejecute DESPUES de crear las tablas
spring.jpa.defer-datasource-initialization=true

# Consola web para ver la base de datos en http://localhost:8080/h2-console
spring.h2.console.enabled=true
