name: Revision automatica - Angela

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hola Mundo
        run: echo "Hola Mundo"
