name: Validacion de Pull Request a Main - Ivan

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Compilar y Testear
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Ejecutar Maven Build y Tests
        run: mvn clean test